PHM:
  alpha_depend_score: 1.0
  alpha_slide_window: 0.01
  alpha_slide_window_reordered_word: 1.0
  alpha_slide_window_word: 2.5
  alpha_slide_window_word_inside: 0.1
  alpha_story_dot_answer_words: 1.0
  answer_ensemble: mlp
  dropout_p: 0.5
  filter_size: 3
  gaussian_sd_reordered_word: 15
  gaussian_sd_word: 10
  gaussian_sd_word_inside: 2
  l1: 0.0
  l2: 0.001
  leaky_alpha: 1
  mean_type: bilinear
  mlp_output_dim: 300
  ngram_inputs: [3]
  sentence_ensemble: mlp
  top_n: 2
  top_n_use_sum: false
  top_n_wordbyword: true
  trainable_answer_ensemble: true
  trainable_answer_plus_question_mlp: true
  trainable_depend: true
  trainable_qa_idf_weight: true
  trainable_sentence_ensemble: true
  trainable_slide_window: false
  trainable_slide_window_reordered_word: true
  trainable_slide_window_word: true
  trainable_slide_window_word_inside: true
  trainable_story_dot_answer_words: false
  trainable_story_encoding_mlp: true
  trainable_word_mlp: false
  trainable_word_weight: false
  use_depend_score: True
  use_gaussian_window: false
  use_gaussian_window_reordered_word: true
  use_gaussian_window_word: true
  use_gaussian_window_word_inside: true
  use_qa_idf: true
  use_slide_window_inside_sentence: true
  use_slide_window_reordered_word: true
  use_slide_window_sentence: true
  use_slide_window_word: true
  window_size_reordered_word: 25
  window_size_word: 25
  window_size_word_inside: 5
  wordbyword_merge_type: mask_average
layers:
  embedding:
    embedding_size: 300
    path: /data/workspace/w2v/GoogleNews-vectors-negative300.bin.gz
    regularizer_alpha: 0
    share_parameter: true
    trainable: false
    type: google
  sentence_encode:
    init_type: idfs
    share_parameter: true
    trainable: false
    type: weight-sum
optimizer:
  clipnorm: 40
  clipvalue: 30
  learning_rate: 0.003
  loss: ranking_loss
  ranking_loss_margin: 0.01
  step_rule: adam
